[project]
name = "equivit"
authors = [
    {name="Chih-Chun Wang", email="mike.wang96029@gmail.com"},
]
version = "0.0.1"
description = "Build and test equivariant Vision Transformers."
readme = "README.md"
requires-python = ">=3.12"

[project.urls]
Homepage = "https://github.com/michael-960/equivit"

[tool.pytest.ini_options]
testpaths = ["tests"]